// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-SJKacY_NCNuoaa8MYzmQc_1fNKgeyJg',
    appId: '1:211843255527:web:9e6573c2d259ed34cde642',
    messagingSenderId: '211843255527',
    projectId: 'bustrackingapp-6d421',
    authDomain: 'bustrackingapp-6d421.firebaseapp.com',
    storageBucket: 'bustrackingapp-6d421.firebasestorage.app',
    measurementId: 'G-X4J4HQWF25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKtBlcymXzL_b_t2gaVZP3WHslGE8yNTs',
    appId: '1:211843255527:android:be8ab2785e1861e4cde642',
    messagingSenderId: '211843255527',
    projectId: 'bustrackingapp-6d421',
    storageBucket: 'bustrackingapp-6d421.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmDv9TLLW2x36c30Nrq0iUilOpW5kwwcM',
    appId: '1:211843255527:ios:6c33cabc7eeed058cde642',
    messagingSenderId: '211843255527',
    projectId: 'bustrackingapp-6d421',
    storageBucket: 'bustrackingapp-6d421.firebasestorage.app',
    iosBundleId: 'com.example.busTrackingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmDv9TLLW2x36c30Nrq0iUilOpW5kwwcM',
    appId: '1:211843255527:ios:6c33cabc7eeed058cde642',
    messagingSenderId: '211843255527',
    projectId: 'bustrackingapp-6d421',
    storageBucket: 'bustrackingapp-6d421.firebasestorage.app',
    iosBundleId: 'com.example.busTrackingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-SJKacY_NCNuoaa8MYzmQc_1fNKgeyJg',
    appId: '1:211843255527:web:2b46aff207bbaec8cde642',
    messagingSenderId: '211843255527',
    projectId: 'bustrackingapp-6d421',
    authDomain: 'bustrackingapp-6d421.firebaseapp.com',
    storageBucket: 'bustrackingapp-6d421.firebasestorage.app',
    measurementId: 'G-2DEQ8D28C8',
  );
}
